# Projet : NovaMarket

##  Contexte

Expliquer le contexte métier, le rôle

## 1.  Importation des bibliothèques

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

## 2. Chargement et aperçu des données

In [6]:
df = pd.read_excel("PNRao_E-commerce_Orders.xlsx")
df.head()

     OrderID CustomerID   OrderDate OrderStatus  TotalAmount
0  ORD-50001  CUST-2322  2025-01-04     Pending     14956.84
1  ORD-50002  CUST-4380  2025-04-03   Cancelled      4644.10
2  ORD-50003  CUST-3034  2023-04-28     Pending     33104.10
3  ORD-50004  CUST-3444  2025-08-14     Shipped     20804.93
4  ORD-50005  CUST-3725  2024-03-17   Delivered     23571.57

## 3. Exploration rapide des données

In [11]:
df.describe().round(2)

       TotalAmount
count      5000.00
mean      28619.13
std       17269.53
min        1280.70
25%       14683.88
50%       26578.24
75%       40054.95
max       96989.52